#service
#server:
#    port: 7788

#datasource
spring:
    datasource:
        initialize: true # Populate the database using 'data.sql'.
        name: csssds
        platform: all # Platform to use in the schema resource (schema-${platform}.sql).
        separator: ; # Statement separator in SQL initialization scripts.
        sql-script-encoding: utf-8 # SQL scripts encoding.
        type: com.alibaba.druid.pool.DruidDataSource # Fully qualified name of the connection pool implementation to use. By default, it is auto-detected from the classpath.
        url: jdbc:mysql://192.168.1.230:3306/portal?useUnicode=true&characterEncoding=UTF-8&useSSL=true # JDBC url of the database.
        username: root
        password: 1234
        
#连接池的配置信息  
        initialSize: 5  
        minIdle: 5  
        maxActive: 20  
        maxWait: 60000  
        timeBetweenEvictionRunsMillis: 60000  
        minEvictableIdleTimeMillis: 300000  
        validationQuery: SELECT '1'
        testWhileIdle: true  
        testOnBorrow: true  
        testOnReturn: false  
        poolPreparedStatements: true  
        maxPoolPreparedStatementPerConnectionSize: 20  
        filters: stat,wall  
        
# JPA 
    jpa:
        generate-ddl: true
        show-sql: true     
        
    aop:
        proxy-target-class: true
        
    servlet:
        load-on-startup: -1
        static-path-pattern: /**
        
    mvc:
        view:
          prefix: /WEB-INF/views/
          suffix: .jsp 
#          static-path-pattern: /**
#        resources:
#           static-locations: file:${web.upload-path}
            
          
    mybatis:
        mapperLocations: classpath:mapper/**/*.xml
        
 #热部署生效
    devtools:
        restart:
            enabled: true

web:
  upload-path: D:/upload/img/
    



